services:

  se5_postgres:
    image: postgres
    container_name: se5_postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=se5-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  se5_pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: se5_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '5050:80'
    depends_on:
      - se5_postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  se5_redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data

  se5_mailhog:
    image: mailhog/mailhog
    restart: always 
    ports:
      - '1025:1025'
      - '8025:8025'
  

volumes:
  pgdata:
  pgadmin_data:
  redis_data:
